server {
    listen ${PORT};
    root /usr/share/nginx/html;
    index index.html;

    # Redirige todas las rutas al index.html para que Angular Router funcione
    # $$ se convierte en $ tras envsubst, dejando $uri intacto para nginx
    location / {
        try_files $$uri $$uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
